<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_logout</name>
   <tag></tag>
   <elementGuidId>abfbe223-5052-4af3-a1cd-91a2974aca5e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/header[1]/div[1]/ul[1]/li[2]/button[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) &gt; [role="menuitem"]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid = 'user-menu-logout' and (text() = 'Log out' or . = 'Log out') and @role = 'menuitem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid="user-menu-logout"]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>custom_data_attr</name>
      <type>Main</type>
      <value>{"testid": "user-menu-logout"}</value>
      <webElementGuid>b7c304b0-fea3-4300-8f21-5298c5bd954e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>user-menu-logout</value>
      <webElementGuid>a219741b-4dc5-4dc2-b892-de7143265266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>8c959c88-50d3-4ee1-a472-1834642ac3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log out</value>
      <webElementGuid>5103ca41-01b8-47a5-8fb2-55bceba6389c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
