<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>aside_dashboard</name>
   <tag></tag>
   <elementGuidId>d8d65ba8-38b9-4ae8-8125-a116acd17ee5</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/aside[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.side</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'side open' and (text() = 'PPaystone HRDashboardEmployeesPayroll runsCost redistributionLeave requestsSettings' or . = 'PPaystone HRDashboardEmployeesPayroll runsCost redistributionLeave requestsSettings')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>aside</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>side open</value>
      <webElementGuid>cd8c0b7a-c1d7-416f-9ff3-064af6bc33f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PPaystone HRDashboardEmployeesPayroll runsCost redistributionLeave requestsSettings</value>
      <webElementGuid>9d87f28b-ecbb-4b3f-b9e7-a5672b3b01a6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
