<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_saveChanges</name>
   <tag></tag>
   <elementGuidId>549354c3-b55c-412b-9e65-7d07774017bd</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/main[1]/div[3]/div[1]/div[3]/button[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.modal-foot &gt; [class="btn"]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid = 'employee-save' and @class = 'btn' and (text() = 'Save changes' or . = 'Save changes')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid="employee-save"]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>f937c44a-ce01-4efb-b89f-649014f07de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>custom_data_attr</name>
      <type>Main</type>
      <value>{"testid": "employee-save"}</value>
      <webElementGuid>58174c0f-bd0d-4f78-8cce-15b87bbb2ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>employee-save</value>
      <webElementGuid>06a2d44a-379e-43d3-b47a-52abef9b025a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save changes</value>
      <webElementGuid>5c918493-141e-4b19-b236-f36b12363080</webElementGuid>
   </webElementProperties>
</WebElementEntity>
