<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_openMenu</name>
   <tag></tag>
   <elementGuidId>bf76c660-f2c8-415d-8ce0-e2de85c5410e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/header[1]/button[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.icon-btn</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'icon-btn burger' and (text() = '☰' or . = '☰')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label="Open menu"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Open menu</value>
      <webElementGuid>0bff2878-8364-4a84-8241-c327224f81df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-btn burger</value>
      <webElementGuid>3cad2a26-9aad-4369-bd36-ce58b9892bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>☰</value>
      <webElementGuid>4e2bb8c9-5b88-4474-9024-1963be5d7a12</webElementGuid>
   </webElementProperties>
</WebElementEntity>
