<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_employeesHeader</name>
   <tag></tag>
   <elementGuidId>e1fb01b3-7d29-4102-9a65-412caad1418f</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/main[1]/div[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.page-head</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'page-head row' and (text() = 'Employees0 of 24 peopleAdd employee' or . = 'Employees0 of 24 peopleAdd employee')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div &gt;&gt; internal:text="Employees0 of 24 peopleAdd employee"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-head row</value>
      <webElementGuid>173a2042-94f8-4934-86fe-eea0d08513a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employees0 of 24 peopleAdd employee</value>
      <webElementGuid>65aca403-9ee5-4de5-8501-7712eb319334</webElementGuid>
   </webElementProperties>
</WebElementEntity>
