<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_employee</name>
   <tag></tag>
   <elementGuidId>3476ddb8-4e47-4e8c-987d-39bc3bef1cdb</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/main[1]/div[3]/table[1]/tbody[1]/tr[2]/td[1]/a[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid = 'employee-link-EMP-1006' and @href = '/employees/EMP-1006' and (text() = '${link_employee_nameRedacted} ${link_employee_nameRedacted}' or . = '${link_employee_nameRedacted} ${link_employee_nameRedacted}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid="employee-link-EMP-1006"]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>custom_data_attr</name>
      <type>Main</type>
      <value>{"testid": "employee-link-EMP-1006"}</value>
      <webElementGuid>9cea818d-d9ea-477c-9176-9712e6beb6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>employee-link-EMP-1006</value>
      <webElementGuid>94026370-e0ab-4d6a-ac14-96e5ffed9fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/employees/EMP-1006</value>
      <webElementGuid>2bec617f-d314-4af7-8a1e-aaef0712840a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${link_employee_nameRedacted} ${link_employee_nameRedacted}</value>
      <webElementGuid>afe7671f-32ab-4d10-871a-ab1f209078c5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
