<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>span_approved</name>
   <tag></tag>
   <elementGuidId>7ca4cb61-b664-4085-831d-3aac54064dde</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/main[1]/section[1]/ul[1]/li[1]/span[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="badge\ b-approved"]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'badge b-approved' and (text() = 'Approved' or . = 'Approved')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span &gt;&gt; internal:text="Approved"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge b-approved</value>
      <webElementGuid>18ab681b-6f68-4dd5-a9af-9d02a3734b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approved</value>
      <webElementGuid>35f451e0-9517-4f36-be38-edf30c715e2c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
